### ISSUE TITLE
Team not handling issues the right way

### ISSUE THREAD

**Issue by ThePhoenix47** [Sertex-Team/sPhone#12]
You can't just lock off every issue asking to publish the source, you may say you don't want to, but you have to leave the issues the way they are. It is unacceptable to simply change the issue to "i'm an idiot" because you don't like it! Also, these php pages are 5min of work, if you don't want to publish them, I'll do. Why is it so important to you to keep them closed-source? This is an open-source project, after all. And please, don't just lock this and make me say i'm an idiot, because that's what a five-year-old does, I hope you have learned to behave yourself better. Just think about what I said and give me a serious answer, and if you keep the server code closed-source, then please tell me the reason why.

**Comment by Ale32bit** [comment]
We don't need to tell you the story.
Please use the Issues tab for sPhone errors
